export const camps = [
  {
    id: '1',
    createdAt: new Date(),
    updatedAt: new Date(),
    year: '2021',
    name: 'name 1',
    url: 'url 1',
    contact_email: 'contact_email 1',
    hometown: 'hometown 1',
    description: 'description 1',
    location_string: 'location_string 1',
    locationId: 1,
  },
  {
    id: '2',
    createdAt: new Date(),
    updatedAt: new Date(),
    year: '2021',
    name: 'name 2',
    url: 'url 2',
    contact_email: 'contact_email 2',
    hometown: 'hometown 2',
    description: 'description 2',
    location_string: 'location_string 2',
    locationId: 2,
  },
  {
    id: '3',
    createdAt: new Date(),
    updatedAt: new Date(),
    year: '2021',
    name: 'name 3',
    url: 'url 3',
    contact_email: 'contact_email 3',
    hometown: 'hometown 3',
    description: 'description 3',
    location_string: 'location_string 3',
    locationId: 3,
  },
];
